[package]
name = "llama"
version = "0.1.0"
authors = ["Federico Mora <fmorarocha@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
rustc-serialize = "0.3.*"
docopt = "1"
serde = { version = "1", features = ["derive"] }
parking_lot = "0.6"
bit-vec = "0.6.1"