[package]
name = "llama"
version = "0.1.0"
authors = ["Federico Mora <fmorarocha@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
pest = "2.1.2"
pest_derive = "2.1.0"
log = "0.4"
env_logger = "0.7.1"
multimap = "0.8.0"