[package]
name = "llama-synth"
version = "0.1.0"
authors = ["Federico Mora <fmorarocha@gmail.com>"]
edition = "2018"

[dependencies]
petgraph = "0.4.13"
pest = "2.1.2"
pest_derive = "2.1.0"
log = "0.4"
env_logger = "0.7.1"